before:
  hooks:
    - go mod tidy
    - go install github.com/tc-hib/go-winres@latest
    - sh -c "sed 's/{{VERSION_FULL}}/{{ .Version }}.0/g; s/{{VERSION}}/{{ .Version }}/g' winres/winres.template.json > winres/winres.json"
    - go-winres make --in winres/winres.json --out cmd/hermes/rsrc_windows

builds:
  - id: "hermes"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/hermes/
    binary: hermes
    ldflags:
      - -s -w -X 'main.Version={{.Version}}' -X 'main.BuildTime={{.Date}}' -X 'main.Commit={{.Commit}}'

archives:
  - id: "hermes"
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
